export default {
  name: 'youju-server',
  nodeFunctions: {
    runtime: 'nodejs18',
    timeout: 30,
    memory: 512,
  },
  routes: [
    {
      pattern: '/api/*',
      function: 'api',
    },
  ],
  env: [
    'DATABASE_URL',
    'AI_API_KEY',
    'AI_BASE_URL',
    'AI_MODEL',
    'AI_MAX_CONCURRENCY',
    'JWT_SECRET',
    'ANALYSIS_CACHE_TTL_MS',
    'ANALYSIS_CACHE_MAX_ENTRIES',
    'ENABLE_SCENARIO_PREHEAT',
    'ENABLE_BACKGROUND_JOBS',
    'EMBEDDING_API_KEY',
    'EMBEDDING_BASE_URL',
    'EMBEDDING_MODEL',
    'RERANKER_API_KEY',
    'RERANKER_BASE_URL',
    'RERANKER_MODEL',
    'VECTOR_SIMILARITY_THRESHOLD',
    'CHAT_MAX_TOKENS',
    'LANGFUSE_SECRET',
    'LANGFUSE_PUBLIC_KEY',
    'LANGFUSE_HOST',
    'DB_DRIVER',
    'CRON_SECRET',
    'URL_FETCH_ALLOWLIST',
    'URL_FETCH_DENYLIST',
  ],
}
